language: dart
dart:
  - stable
os:
  - linux
install:
  - echo 'Skip default Travis CI install step' # this is to avoid an error with pub in Travis
before_deploy:
  - chmod +x ./.travis/publish.sh # giving execution permissions to this file to avoid error 127.
  - mv ./.travis ../ # moving this out the publication folder as we don't want to publish it.
deploy:
    provider: script
    script: ../.travis/publish.sh
    on:
      tags: true
