version: '3.3'
services:
  app:
    container_name: appcertimax
    image: appcertimax:latest
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      app-network:
        ipv4_address: 172.18.0.4
    ports:
      - "3000:80"

#Docker Networks
networks:
  app-network:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 172.18.0.0/24